package com.tencent.devops.plugin.processor

import com.tencent.devops.plugin.api.ExtensionType
import java.io.BufferedWriter
import java.io.OutputStream
import java.io.OutputStreamWriter
import java.nio.charset.StandardCharsets.UTF_8

/**
 * Extension配置文件工具类
 */
object ExtensionFiles {

    /**
     * 将扩展类名写入文件
     */
    fun write(factories: MutableMap<ExtensionType, MutableSet<String>>, output: OutputStream) {
        BufferedWriter(OutputStreamWriter(output, UTF_8)).use { writer ->
            writer.write("# Generated by DevOps Boot\n")
            factories.forEach { (key, value) ->
                writer.write(key.identifier)
                writer.write("=\\\n  ")
                val names = value.joinToString(",\\\n  ")
                writer.write(names)
                writer.newLine()
            }
        }
    }
}
