# Create release branch from master or hotfix
name: Create release branch
on:
  workflow_dispatch:
    inputs:
      release_version:
        description: "指定发布版本，默认根据项目语义化版本进行迭代"
        required: false
      next_version:
        description: "指定下一个开发版本，默认根据项目语义化版本进行迭代"
        required: false

jobs:
  create-release:
    runs-on: ubuntu-latest
    env:
      RELEASE_VERSION: ${{ github.event.inputs.release_version }}
      NEXT_VERSION: ${{ github.event.inputs.next_version }}
    steps:
      - name: Check branch
        if: github.ref_name != 'master' && startsWith(github.ref_name,'hotfix-') != true
        run: |
          echo "Create release branch can only from master or hotfix-** branch"
          exit 1
      - uses: actions/checkout@v2
      - name: Setup git configuration
        run: |
          git config user.name "bkci-bot"
          git config user.email "64278246+bkci-bot@users.noreply.github.com"
      - name: Release
        run: |
          ./gradlew release -Prelease.releaseVersion=${{ env.RELEASE_VERSION }} -Prelease.developmentVersion=${{ env.NEXT_VERSION }}
      - name: Push new release branch
        run: |
          version=$([ -z "${{ env.RELEASE_VERSION }}" ] && cat version.txt || echo "${{ env.RELEASE_VERSION }}")
          release_branch=release-$version
          echo "version=$version"
          echo "branch_name=$release_branch"
          git checkout -b $release_branch v$version
          git push origin $release_branch